######################################################################
##
## Filename: Core_TB.udo
## Created on: Sun Mar 16 2:03:11 PM Iran Daylight Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
